spring:
  application:
    name: image-service

  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/image_db
    username: amihady
    password: amihady
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration


minio:
  url: http://localhost:9000
  accessKey: admin
  secretKey: password
  bucketName: products-images
  urlExpiration: 3600
