version: '3.8'

services:
  image_ps:
    image: postgres:latest
    container_name: image_ps
    restart: always
    environment:
      POSTGRES_USER: amihady
      POSTGRES_PASSWORD: amihady
      POSTGRES_DB: image_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio-data:/data

  redis:
    image: redis:latest
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:
  minio-data:
  redis_data:

